<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MLIVE-LP00960" name="Profile Test" tests="1" failures="1" timestamp="10 Apr 2019 19:38:21 GMT" time="38.392" errors="0">
  <testcase name="testProfile" time="37.37" classname="com.qtpselenium.facebook.pom.testcases.ProfileTest">
    <failure type="java.lang.AssertionError" message="Login failed">
      <![CDATA[java.lang.AssertionError: Login failed
	at com.qtpselenium.facebook.pom.testcases.ProfileTest.testProfile(ProfileTest.java:44)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testProfile -->
</testsuite> <!-- Profile Test -->
